### ISSUE TITLE
Can not create output

### ISSUE THREAD

**Issue by huyphongdo** [AbnerCSZ/lidar2rosbag_KITTI#2]
I have try your instruction but I can not create output after executed cmd:
rosrun lidar2rosbag lidar2rosbag /data/KITTI/dataset/sequences/04/ 04
it just inform: Segmentation fault
Can you give me some advice?

**Comment by Marcus2113** [comment]
Same issue...were you able to resolve it or find another method to convert velodyne kitti datasets?

**Comment by huyphongdo** [comment]
haven't yet but now I used Kitti2bag with rawdata. I could try it.

**Comment by HongweiSunny** [comment]
> I have try your instruction but I can not create output after executed cmd:
> rosrun lidar2rosbag lidar2rosbag /data/KITTI/dataset/sequences/04/ 04
> it just inform: Segmentation fault
> Can you give me some advice?

the first argument is the path of kitti_dataset,so you need you change it to your local path where you save kitti_dataset . maybe you need to check the source code of this package.

**Comment by HongweiSunny** [comment]
> I have try your instruction but I can not create output after executed cmd:
> rosrun lidar2rosbag lidar2rosbag /data/KITTI/dataset/sequences/04/ 04
> it just inform: Segmentation fault
> Can you give me some advice?

Hi，may there are no time.txt file in your sequence directory. You should check it.

**Comment by jkstyle2** [comment]
same segmentation fault error. any solver you found?

**Comment by AbnerCSZ** [comment]
Hi! @jkstyle2 @Marcus2113 @huyphongdo 
Please confirm that the input path contains the file `times.txt` and the folder `velodyne`. Specific examples can refer to the latest `README.md`.  
I hope this helps you!

**Comment by ajung37** [comment]
I've checked that my input path includes the times.txt and the folder velodyne. I also referenced the latest README.md and I still am getting the Segmentation fault error. Any ideas to troubleshoot this issue. Thanks!
![Screenshot from 2021-07-15 15-18-07](https://user-images.githubusercontent.com/87497149/125845044-b9326dbc-249e-4543-9d41-3026f68ee7f6.png)
