### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by TranquilityOcean** [AbnerCSZ/lidar2rosbag_KITTI#6]
/usr/include/lz4.h:249:72: error: conflicting declaration ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;

my environment: ubuntu18.04. melodic ,please.thanks.

**Comment by aaxbas** [comment]
You can find a solution here: https://github.com/ethz-asl/lidar_align/issues/16
